### ISSUE TITLE
#135: osx osx_64_python3.7.____73_pypy was canceled

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pytest-feedstock#136]
It looks like the most recent merge to master after #135 failed... might just need a re-kick!

**Comment by nicoddemus** [comment]
Thanks for noticing!

Unfortunately I can't do that myself, perhaps @marcelotrevisani or @ocefpaf can help?

**Comment by marcelotrevisani** [comment]
done!

**Comment by marcelotrevisani** [comment]
https://github.com/conda-forge/pytest-feedstock/runs/2685134287

**Comment by nicoddemus** [comment]
Thanks!
