### ISSUE TITLE
yank pytest 8.1.0 ?

### ISSUE THREAD

**Issue by chaen** [conda-forge/pytest-feedstock#177]
### Comment:

Hi,

The release 8.1.0 of `pytest` has been yanked on `pypi` due to https://github.com/pytest-dev/pytest/issues/12069

Is there a similar workflow planned for condaforge ? 
Thanks !

**Comment by nicoddemus** [comment]
Hi,

Already done, you can see that the package has the label `broken`: https://anaconda.org/conda-forge/pytest/files
