### ISSUE TITLE
Broken on windows

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/pytest-feedstock#24]
I think #23 moving to noarch has broken windows. I'm seeing this on AppVeyor:

<img width="853" alt="screen shot 2017-09-07 at 3 50 24 pm" src="https://user-images.githubusercontent.com/221526/30186830-61c05270-93e4-11e7-9828-aa5da8c3dc5a.png">

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by dopplershift** [comment]
Hmmm....worked locally on a windows vm. Conda on AppVeyor is 4.3.11. What do we need for noarch?

**Comment by nicoddemus** [comment]
Also works for me. Perhaps `noarch` needs conda `4.3`?

**Comment by nicoddemus** [comment]
```
C:\Users\Bruno>activate test-noarch

(test-noarch) C:\Users\Bruno>pytest --version
This is pytest version 3.2.2, imported from D:\Programming\Miniconda3\envs\test-noarch\lib\site-packages\pytest.py

(test-noarch) C:\Users\Bruno>conda list
# packages in environment at D:\Programming\Miniconda3\envs\test-noarch:
#
certifi                   2017.7.27.1              py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pytest                    3.2.2                      py_0    conda-forge
python                    3.6.2                         0    conda-forge
setuptools                36.3.0                   py36_0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
wincertstore              0.2                      py36_0    conda-forge
```

**Comment by mzuehlke** [comment]
Hi, we are also seeing errors on AppVeyor with builds using pytest 3.2.2 (not with 3.2.1)

    py.test -v --cov=cate test
    usage: py.test-script.py [options] [file_or_dir] [file_or_dir] [...]
    py.test-script.py: error: unrecognized arguments: --cov=cate
        inifile: None
        rootdir: C:\projects\cate-core

See https://ci.appveyor.com/project/ccitools/cate-core/build/956#L821

**Comment by dopplershift** [comment]
So the key is to not use the pre-installed miniconda on AppVeyor, but make sure to update conda:
```
conda update -q conda
```

Doing so fixes the problem for me, so the problem really lies with trying to use conda 4.3.11 with the noarch packages (at least on AppVeyor).

**Comment by mzuehlke** [comment]
In my example that doesn't help:

    The following packages will be UPDATED:
        conda: 4.3.11-py36_0 --> 4.3.25-py36_0

https://ci.appveyor.com/project/ccitools/cate-core/build/956#L7

**Comment by dopplershift** [comment]
@mzuehlke your problem is completely different--it looks like it isn't finding pytest-cov for some reason. Probably best to open a separate issue.

**Comment by nicoddemus** [comment]
@dopplershift thanks for coming back to confirm that indeed we need `conda` >= 4.3 to use `noarch` packages. I'm closing this then.

@mzuehlke feel free to open another issue, but as @dopplershift said your problem seems that `pytest-cov` is not installed.

**Comment by TimoRoth** [comment]
Our builds got broken by this as well:
https://ci.appveyor.com/project/TimoRoth/oggm/build/1.0.4

Here's the same build with debug output turned on:
https://ci.appveyor.com/project/TimoRoth/oggm/build/1.0.5

The error:
```
INFO conda.core.link:_execute_actions(319): ===> LINKING PACKAGE: conda-forge::pytest-3.2.2-py_0 <===
  prefix=C:\Python3-conda64
  source=C:\Python3-conda64\pkgs\pytest-3.2.2-py_0
DEBUG conda.core.link:_execute_actions(331): Error in action #60 for pkg_idx #89 LinkPathAction(target_prefix='C:\\Python3-conda64', target_short_path='Scripts/py.test.exe', source_prefix='C:\\Python3-conda64', source_short_path='Scripts/conda.exe', link_type=<LinkType.hardlink: 1>, _execute_successful=False, _verified=True)
Traceback (most recent call last):
  File "C:\Python3-conda64\lib\site-packages\conda\core\link.py", line 326, in _execute_actions
  File "C:\Python3-conda64\lib\site-packages\conda\core\path_actions.py", line 245, in execute
  File "C:\Python3-conda64\lib\site-packages\conda\gateways\disk\create.py", line 241, in create_link
conda.CondaError: Cannot link a source that does not exist. C:\Python3-conda64\Scripts\conda.exe
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::pytest-3.2.2-py_0'.
CondaError: Cannot link a source that does not exist. C:\Python3-conda64\Scripts\conda.exe
Attempting to roll back.
```

The conda version is more than recent enough to support noarch.

**Comment by nicoddemus** [comment]
Hi @TimoRoth 

Which version are you using? Did you try this tip from @dopplershift ?

> So the key to fixing my issue is to not use the pre-installed miniconda on AppVeyor, but make sure to update conda

**Comment by TimoRoth** [comment]
Our AppVeyor script downloads and installs the latest version of Miniconda3 on every run.
The conda version that ends up using is 4.3.25-py36_0.

I found a workaround for now, which is: `conda update -c conda-forge --all`

That downloads/superseeds a whole bunch of packages, and in fact ends up with conda 4.3.23-py36_0, so a bit older than the version from the default channels.

After doing that, installing pytest works fine.

**Comment by nicoddemus** [comment]
Thanks @TimoRoth for the update. I think we might get away with `conda update conda -c conda-forge --no-deps` to just update `conda` and leave the other packages alone.

@goanpeca or @kalefranz, do you have any idea what might be going on here?

**Comment by kwilcox** [comment]
The `noarch` changes broke a ton of my builds/pipelines. I'm still on Python 3.5 in some root environments and anaconda 4.2 is the last version that was built with 3.5. In Anaconda's documentation I'm doing what the third bullet is: https://docs.anaconda.com/anaconda/faq#id3. I'll switch my pipelines to the second bullet... Just commenting here so another lost soul might be helped.

**Comment by nicoddemus** [comment]
Thanks @kwilcox for writing up.

>  I'm still on Python 3.5 in some root environments and anaconda 4.2 is the last version that was built with 3.5.

That's strange, I use Python 3.5 with the latest conda 4.3. Are you unable to upgrade?

**Comment by kwilcox** [comment]
Yes, of course I can upgrade to Miniconda>4.2 and install `python=3.5` into the root environment to replace the existing `python=3.6`. I was avoiding that by using a Miniconda build that came with `python=3.5` by default. Basically a timebomb that just went off. :bomb: ... :boom:.

**Comment by nicoddemus** [comment]
> Yes, of course I can upgrade to Miniconda>4.2 and install python=3.5 into the root environment to replace the existing python=3.6.

You can update the conda version in the root without re-installing Miniconda by using `conda update conda -n root`, I believe.

**Comment by ocefpaf** [comment]
Yep. I still use miniconda that comes with the CIs and just to a `conda update conda` as the first step.
Sometimes I do a `conda update --all` too :smile:

**Comment by kwilcox** [comment]
Is `conda update conda -n root` suppose to bump MINOR versions or just PATCH versions? `4.3.23` isn't upgrading to `4.4.0` and `4.2.13` isn't upgrading to a version that would support `noarch`... thus my solution to upgrade Miniconda and then downgrade the python version.

```
$ conda update conda -n root --dry-run
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/kwilcox/miniconda3-py36:
#
conda                     4.3.23                   py36_0    conda-forge
```

```
$ conda update conda -n root --dry-run
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/kwilcox/miniconda3:
#
conda                     4.2.13                   py35_0    conda-forge
```

We don't have to keep iterating on this issue... just wanted to point out to people landing here from Google what a possible solution could be!
