### ISSUE TITLE
No support for py35

### ISSUE THREAD

**Issue by chrisRedwine** [conda-forge/pytest-feedstock#80]
Hello - Is there a reason why the pytest conda package isn't being built for py35, as the library appears to support it?

**Comment by nicoddemus** [comment]
`conda-forge` in general stopped supporting `py35` after adopting `py37`. AFAICT conda-forge aims to support py27 and the last two Python 3 releases (currently `py36` and `py37`). I suppose when `py38` gets released `conda-forge` will also slowly drop `py36` from new packages.

@ocefpaf might want to add here.

Closing this for now as I believe your question has been answered, but please feel free to follow up with further questions. 👍

**Comment by ocefpaf** [comment]
> @ocefpaf might want to add here.

Nope. You cover it all :smile: Thanks!
